{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "k8ecr-autodeploy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "k8ecr-autodeploy.fullname" . }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
      - update
      - get
{{- end -}}
