apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "k8ecr-autodeploy.fullname" . }}
  labels:
    app: {{ template "k8ecr-autodeploy.name" . }}
    chart: {{ template "k8ecr-autodeploy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "k8ecr-autodeploy.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "k8ecr-autodeploy.name" . }}
        release: {{ .Release.Name }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE
              value: {{ required "A target namespace is required." .Values.targetNamespace }}
            - name: WEBHOOK
              value: {{ .Values.webhookUrl }}
            - name: AWS_REGION
              value: {{ required "An AWS region is required" .Values.awsRegion }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "k8ecr-autodeploy.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
